# input and output paths, either relative to the project root or absolute paths. 
data_dir: data
output_dir: output

elmer_geo_layers: # elmer geo layers to download
  # name, sql table
  parcels_pts: PARCELS_URBANSIM_2023_PTS
  cities: CITIES


#---------------------------------------------------------------------------------------------------
overlay_settings:
  # FLU table path and juris_zn column
  flu_table_path: C:/Users/JKolberg/OneDrive - PSRC/GIS - Projects/FLU/Zoning_2026_d3.xlsx
  flu_juris_zn_col: juris_zn
  
  # GDB that contains the overlay layers for each jurisdiction. Specify the jurisdiction name that
  # matches the juris column in the FLU table and either the juris_zn_col or zone_col for each layer.
  overlay_gdb_path: C:/Users/JKolberg/OneDrive - PSRC/GIS - Projects/FLU/FLU_draft2.gdb
  overlay_layers:
    - juris: University_Place
      layer: UP_overlay
      juris_zn_col: Juris_zn

    - juris: Poulsbo
      layer: Poulsbo_overlay
      zone_col: zone_psrc

    - juris: Kitsap
      layer: Silverdale_overlay
      zone_col: zone_psrc

    - juris: Tacoma
      layer: Tacoma_overlays_stacked
      juris_zn_col: Juris_zn
  
  # If True, write the final combined overlays to the input GDB as a new layer. 
  # The layer name is specified in final_overlay_layer_name. Will automatically be written 
  # to the output dir in overlay_layers_merged.gdb
  write_final_overlays_to_input_gdb: False
  final_overlay_layer_name: overlays_combined


#---------------------------------------------------------------------------------------------------
hb1110_settings:
  # input gdb that contains the hb1110 transit walksheds layer
  transit_gdb_path: C:/Users/JKolberg/OneDrive - PSRC/GIS - Projects/FLU/transit_hb_1110.gdb
  transit_walksheds_layer: hb_1110_walksheds # hb1110 input transit walksheds layer name
  
  # if true, output a layer of hb1110 cities and walksheds based on dissolved parcels, can 
  # take a long time to load, so if visual check is not needed, set to false
  output_cities_walkshed: False
  # name of the hb1110 cities and walkshed output layer, must be set if output_cities_walkshed is True
  output_cities_walkshed_name: hb_1110_cities_walkshed # will be saved in output dir in hb_1110_cities_walkshed.gdb


#------------------------------------------------------------------------------------------------
unroll_constraints_settings:
  root_dir: Q:/Projects/2023_Baseyear/FLU_and_Lockouts
  flu_shp: GIS/FLU_2025/FLU_20260522/QC/FLU2025_final.shp # path relative to root_dir
  juris_zn_shp_id: Juris_zn # unique id column in flu_shp
  flu_imputed: imputation_data/final_flu_imputed_2026-06-24.csv # path relative to root_dir
  juris_zn_imputed_id: juris_zn # unique id column in flu_imputed
  base_year_parcel_layer: parcels_urbansim_2023_pts # ElmerGeo layer name for parcel points
  base_year_cache: L:/base_year_2023_inputs/JobParcel/base_year_data/2023/parcels # urbansim baseyear cache

#---------------------------------------------------------------------------------------------------
steps: # pypyr pipeline steps to run
  # - future_land_use.steps.get_elmer_data
  # - future_land_use.steps.combine_overlays
  # - future_land_use.steps.flag_overlay_parcels
  - future_land_use.steps.flag_hb_1110_parcels