# input and output paths, either relative to the project root or absolute paths. 
data_dir: data
output_dir: output


#---------------------------------------------------------------------------------------------------
overlay_settings:
  # FLU table path and juris_zn column
  flu_table_path: C:/Users/JKolberg/OneDrive - PSRC/GIS - Projects/FLU/Zoning_2026_d3.xlsx
  flu_juris_zn_col: juris_zn
  
  # GDB that contains the overlay layers for each jurisdiction. Specify the jurisdiction name that
  # matches the juris column in the FLU table and either the juris_zn_col or zone_col for each layer.
  overlay_gdb_path: C:/Users/JKolberg/OneDrive - PSRC/GIS - Projects/FLU/FLU_draft2.gdb
  overlay_layers:
    - juris: University_Place
      layer: UP_overlay
      juris_zn_col: Juris_zn

    - juris: Poulsbo
      layer: Poulsbo_overlay
      zone_col: zone_psrc

    - juris: Kitsap
      layer: Silverdale_overlay
      zone_col: zone_psrc

    - juris: Tacoma
      layer: Tacoma_overlays_stacked
      juris_zn_col: Juris_zn

  write_final_overlays_to_input_gdb: True
  final_overlay_layer_name: overlays_combined


#---------------------------------------------------------------------------------------------------
hb1110_settings:
  transit_gdb_path: C:/Users/JKolberg/OneDrive - PSRC/GIS - Projects/FLU/transit_hb_1110.gdb
  transit_walksheds_layer: hb_1110_walksheds # hb1110 transit walksheds layer
  output_parcel_layer: hb_1110_parcels
  output_cities_walkshed: True # takes awhile to pull parcel polygons in
  output_cities_walkshed_name: hb_1110_cities_walkshed # must be set if output_cities_walkshed is True


#---------------------------------------------------------------------------------------------------
steps: # pypyr pipeline steps to run
  - future_land_use.steps.combine_overlays
  # - future_land_use.steps.flag_hb_1110_parcels